### PR TITLE
Add support for Smart Lithium

### PR DESCRIPTION
**Pull request by kroese**
I tried to port https://github.com/keshavdv/victron-ble/pull/47 to this fork. Please doublecheck if everything is correct, because I have no Python experience and did not test it.

### Summary 📝
Add initial support for smart lithium batteries

### Details
I've implemented the parsing based on the [pdf](https://community.victronenergy.com/storage/attachments/48745-extra-manufacturer-data-2022-12-14.pdf) and tested on a bunch of 160Ah batteries. @stefanor worked together with Victron to fix the byte order, and the data gathered with this code seems to match what the VictronConnect app says.

### CODE REVIEW

**Comment by gregsyoung** [comment]
did you get verification from others?
i have qty 3 smart lithiums - but im remote from boat for another week .. before i could test.

**Comment by gregsyoung** [comment]
did it finally get tested?
and if so, has it been merged into signalk-victron -ble ?

**Comment by j9brown** [comment]
It looks sensible enough.  I noticed one N/A value from the docs isn't handled here.  I don't own these devices so I can't test them myself.  I'll merge the change and make a couple of tweaks and hope for the best.

**Comment by gregsyoung** [comment]
excellent.. i can test after the updates are merged into signalk-victron-ble plugin,
and will then report back.

thanks for all your efforts.. looking forward to signalk having access to “all” my battery details..

**Pull request merged**
